onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -label clk /cpuSim/clk
add wave -noupdate -label globalReset /cpuSim/globalReset
add wave -noupdate -label result /cpuSim/result
add wave -noupdate -label regDest /cpuSim/regDest
add wave -noupdate -label nextPC /cpuSim/nextPC
add wave -noupdate -label validAddress /cpuSim/cpu/validAddress
add wave -noupdate -label isJAL /cpuSim/cpu/isJAL
add wave -noupdate -label freeze /cpuSim/cpu/freeze
add wave -noupdate -label redirect /cpuSim/cpu/redirect
add wave -noupdate -label predictedPCF /cpuSim/cpu/predictedPCF
add wave -noupdate -label instr /cpuSim/cpu/instr
add wave -noupdate -label instrPC /cpuSim/cpu/instrPC
add wave -noupdate -label GHRIndex /cpuSim/cpu/GHRIndex
add wave -noupdate -label PHTState /cpuSim/cpu/PHTState
add wave -noupdate -label commitRob /cpuSim/cpu/commitRob
add wave -noupdate -label we /cpuSim/cpu/we
add wave -noupdate -label fullRob /cpuSim/cpu/fullRob
add wave -noupdate -label instruction /cpuSim/cpu/instruction
add wave -noupdate -label destRegR /cpuSim/cpu/destRegR
add wave -noupdate -label destROB /cpuSim/cpu/destROB
add wave -noupdate -label robAllocation /cpuSim/cpu/robAllocation
add wave -noupdate -label rob1 /cpuSim/cpu/rob1
add wave -noupdate -label rob2 /cpuSim/cpu/rob2
add wave -noupdate -label robInstr /cpuSim/cpu/robInstr
add wave -noupdate -label operand1 /cpuSim/cpu/operand1
add wave -noupdate -label operand2 /cpuSim/cpu/operand2
add wave -noupdate -label ALUControl /cpuSim/cpu/ALUControl
add wave -noupdate -label immExt /cpuSim/cpu/immExt
add wave -noupdate -label pc /cpuSim/cpu/pc
add wave -noupdate -label RSstation /cpuSim/cpu/RSstation
add wave -noupdate -label branchFunct3 /cpuSim/cpu/branchFunct3
add wave -noupdate -label brnch /cpuSim/cpu/brnch
add wave -noupdate -label jal /cpuSim/cpu/jal
add wave -noupdate -label useImm /cpuSim/cpu/useImm
add wave -noupdate -label regWrite /cpuSim/cpu/regWrite
add wave -noupdate -label isJALR /cpuSim/cpu/isJALR
add wave -noupdate -label isLUI /cpuSim/cpu/isLUI
add wave -noupdate -label isAUIPC /cpuSim/cpu/isAUIPC
add wave -noupdate -label stationRequest /cpuSim/cpu/stationRequest
add wave -noupdate -label destRegW /cpuSim/cpu/destRegW
add wave -noupdate -label busy1 /cpuSim/cpu/busy1
add wave -noupdate -label busy2 /cpuSim/cpu/busy2
add wave -noupdate -label ALUFull /cpuSim/cpu/ALUFull
add wave -noupdate -label branchFull /cpuSim/cpu/branchFull
add wave -noupdate -label state /cpuSim/cpu/state
add wave -noupdate -label predictPC /cpuSim/cpu/predictPC
add wave -noupdate -label rdirect /cpuSim/cpu/rdirect
add wave -noupdate -label robReq /cpuSim/cpu/robReq
add wave -noupdate -label robValue1 /cpuSim/cpu/robValue1
add wave -noupdate -label robValue2 /cpuSim/cpu/robValue2
add wave -noupdate -label branchBusyVector /cpuSim/cpu/branchBusyVector
add wave -noupdate -label ALUBusyVector /cpuSim/cpu/ALUBusyVector
add wave -noupdate -label targetPC /cpuSim/cpu/targetPC
add wave -noupdate -label earlyResult /cpuSim/cpu/earlyResult
add wave -noupdate -label seqPC /cpuSim/cpu/seqPC
add wave -noupdate -label ready1 /cpuSim/cpu/ready1
add wave -noupdate -label ready2 /cpuSim/cpu/ready2
add wave -noupdate -label earlyWrite /cpuSim/cpu/earlyWrite
add wave -noupdate -label jump /cpuSim/cpu/jump
add wave -noupdate -label value1 /cpuSim/cpu/value1
add wave -noupdate -label value2 /cpuSim/cpu/value2
add wave -noupdate -label aluCntrl /cpuSim/cpu/aluCntrl
add wave -noupdate -label branchCntrl /cpuSim/cpu/brnchCntrl
add wave -noupdate /cpuSim/cpu/branchRequests
add wave -noupdate /cpuSim/cpu/ALURequests
add wave -noupdate /cpuSim/cpu/ALURob
add wave -noupdate /cpuSim/cpu/ALUInfo
add wave -noupdate /cpuSim/cpu/aluSrc1
add wave -noupdate /cpuSim/cpu/aluSrc2
add wave -noupdate -label aluAvailable /cpuSim/cpu/aluAvailable
add wave -noupdate -label branchAvailable /cpuSim/cpu/branchAvailable
add wave -noupdate /cpuSim/cpu/bsrc1
add wave -noupdate /cpuSim/cpu/bsrc2
add wave -noupdate /cpuSim/cpu/branchRob
add wave -noupdate /cpuSim/cpu/branchInfo
add wave -noupdate /cpuSim/cpu/predictedAddress
add wave -noupdate /cpuSim/cpu/targetAddress
add wave -noupdate /cpuSim/cpu/branchResult
add wave -noupdate /cpuSim/cpu/ROBValue1
add wave -noupdate /cpuSim/cpu/ROBValue2
add wave -noupdate /cpuSim/cpu/valid1
add wave -noupdate /cpuSim/cpu/valid2
add wave -noupdate /cpuSim/cpu/full
add wave -noupdate /cpuSim/cpu/inputBus/instrPC
add wave -noupdate /cpuSim/cpu/inputBus/oldPC
add wave -noupdate /cpuSim/cpu/inputBus/regStatus
add wave -noupdate /cpuSim/cpu/inputBus/statusSnap
add wave -noupdate /cpuSim/cpu/inputBus/targetAddress
add wave -noupdate /cpuSim/cpu/inputBus/result
add wave -noupdate /cpuSim/cpu/inputBus/PHTIndex
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/targetAddress
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/predictedPC
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/oldPC
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/mispredict
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/misdirect
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/isJAL
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/predictorHit
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/clk
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/freeze
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/globalReset
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/reset
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/redirect
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/nextPC
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/intermediatePC
add wave -noupdate /cpuSim/cpu/fetchStage/pcSelect/pcPlus1
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/resolvedTarget
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/PC
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/oldPC
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/writeBTB
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/clk
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/takenBranch
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/validRead
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/targetAddress
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/valid
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/address
add wave -noupdate /cpuSim/cpu/fetchStage/branchTargetBuffer/btbHit
add wave -noupdate /cpuSim/cpu/fetchStage/predictor/index
add wave -noupdate /cpuSim/cpu/fetchStage/predictor/previousIndex
add wave -noupdate /cpuSim/cpu/fetchStage/predictor/newState
add wave -noupdate /cpuSim/cpu/fetchStage/predictor/clk
add wave -noupdate /cpuSim/cpu/fetchStage/predictor/predictorWrite
add wave -noupdate /cpuSim/cpu/fetchStage/predictor/state
add wave -noupdate /cpuSim/cpu/fetchStage/indexGen/wasTaken
add wave -noupdate /cpuSim/cpu/fetchStage/indexGen/clk
add wave -noupdate /cpuSim/cpu/fetchStage/indexGen/branch
add wave -noupdate /cpuSim/cpu/fetchStage/indexGen/reset
add wave -noupdate /cpuSim/cpu/fetchStage/indexGen/PC
add wave -noupdate /cpuSim/cpu/fetchStage/indexGen/index
add wave -noupdate /cpuSim/cpu/fetchStage/indexGen/globalHistory
add wave -noupdate /cpuSim/cpu/fetchStage/IMem/rAddress
add wave -noupdate /cpuSim/cpu/fetchStage/IMem/clk
add wave -noupdate /cpuSim/cpu/fetchStage/IMem/instr
add wave -noupdate /cpuSim/cpu/decodeStage/clk
add wave -noupdate /cpuSim/cpu/decodeStage/we
add wave -noupdate /cpuSim/cpu/decodeStage/redirect
add wave -noupdate /cpuSim/cpu/decodeStage/ALUFull
add wave -noupdate /cpuSim/cpu/decodeStage/branchFull
add wave -noupdate /cpuSim/cpu/decodeStage/predictedPCF
add wave -noupdate /cpuSim/cpu/decodeStage/GHRIndex
add wave -noupdate /cpuSim/cpu/decodeStage/PHTState
add wave -noupdate /cpuSim/cpu/decodeStage/fullRob
add wave -noupdate /cpuSim/cpu/decodeStage/instruction
add wave -noupdate /cpuSim/cpu/decodeStage/instrPC
add wave -noupdate /cpuSim/cpu/decodeStage/destRegR
add wave -noupdate /cpuSim/cpu/decodeStage/destROB
add wave -noupdate /cpuSim/cpu/decodeStage/commitROB
add wave -noupdate /cpuSim/cpu/decodeStage/robAllocation
add wave -noupdate /cpuSim/cpu/decodeStage/rob1
add wave -noupdate /cpuSim/cpu/decodeStage/rob2
add wave -noupdate /cpuSim/cpu/decodeStage/operand1
add wave -noupdate /cpuSim/cpu/decodeStage/operand2
add wave -noupdate /cpuSim/cpu/decodeStage/ALUControl
add wave -noupdate /cpuSim/cpu/decodeStage/immExt
add wave -noupdate /cpuSim/cpu/decodeStage/pc
add wave -noupdate /cpuSim/cpu/decodeStage/RSstation
add wave -noupdate /cpuSim/cpu/decodeStage/branch
add wave -noupdate /cpuSim/cpu/decodeStage/isJAL
add wave -noupdate /cpuSim/cpu/decodeStage/useImm
add wave -noupdate /cpuSim/cpu/decodeStage/regWrite
add wave -noupdate /cpuSim/cpu/decodeStage/isJALR
add wave -noupdate /cpuSim/cpu/decodeStage/isLUI
add wave -noupdate /cpuSim/cpu/decodeStage/isAUIPC
add wave -noupdate /cpuSim/cpu/decodeStage/stationRequest
add wave -noupdate /cpuSim/cpu/decodeStage/destRegW
add wave -noupdate /cpuSim/cpu/decodeStage/busy1
add wave -noupdate /cpuSim/cpu/decodeStage/busy2
add wave -noupdate /cpuSim/cpu/decodeStage/freeze
add wave -noupdate /cpuSim/cpu/decodeStage/state
add wave -noupdate /cpuSim/cpu/decodeStage/predictPC
add wave -noupdate /cpuSim/cpu/decodeStage/branchFunct3
add wave -noupdate /cpuSim/cpu/decodeStage/rdirect
add wave -noupdate /cpuSim/cpu/decodeStage/robReq
add wave -noupdate /cpuSim/cpu/decodeStage/robInstr
add wave -noupdate /cpuSim/cpu/decodeStage/extImm
add wave -noupdate /cpuSim/cpu/decodeStage/jalr
add wave -noupdate /cpuSim/cpu/decodeStage/lui
add wave -noupdate /cpuSim/cpu/decodeStage/auipc
add wave -noupdate /cpuSim/cpu/decodeStage/stationReq
add wave -noupdate /cpuSim/cpu/decodeStage/regWr
add wave -noupdate /cpuSim/cpu/decodeStage/jal
add wave -noupdate /cpuSim/cpu/decodeStage/brnch
add wave -noupdate /cpuSim/cpu/decodeStage/memWr
add wave -noupdate /cpuSim/cpu/decodeStage/occupied1
add wave -noupdate /cpuSim/cpu/decodeStage/occupied2
add wave -noupdate /cpuSim/cpu/decodeStage/immUse
add wave -noupdate /cpuSim/cpu/decodeStage/robWrite
add wave -noupdate /cpuSim/cpu/decodeStage/station
add wave -noupdate /cpuSim/cpu/decodeStage/aluC
add wave -noupdate /cpuSim/cpu/decodeStage/regValue1
add wave -noupdate /cpuSim/cpu/decodeStage/regValue2
add wave -noupdate /cpuSim/cpu/decodeStage/src1ROB
add wave -noupdate /cpuSim/cpu/decodeStage/src2ROB
add wave -noupdate /cpuSim/cpu/decodeStage/regStatus
add wave -noupdate /cpuSim/cpu/decodeStage/op1
add wave -noupdate /cpuSim/cpu/decodeStage/op2
add wave -noupdate /cpuSim/cpu/decodeStage/noRS
add wave -noupdate /cpuSim/cpu/decodeStage/commitInfo
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/instrPC
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/oldPC
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/regStatus
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/statusSnap
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/targetAddress
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/result
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/PHTIndex
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/previousIndex
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/controlFlow
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/destination
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/destCommit
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/commitInfo
add wave -noupdate /cpuSim/cpu/decodeStage/robBus/validCommit
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/instrPC
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/oldPC
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/regStatus
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/statusSnap
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/targetAddress
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/result
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/PHTIndex
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/previousIndex
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/controlFlow
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/destination
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/destCommit
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/commitInfo
add wave -noupdate /cpuSim/cpu/decodeStage/inputBus/validCommit
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/instruction
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/ALUControl
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/immExt
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/RSstation
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/memWrite
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/branch
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/isJAL
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/useImm
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/regWrite
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/isJALR
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/isLUI
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/isAUIPC
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/stationRequest
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/robWrite
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/immSrc
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/aluOp
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/opcode
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/destReg
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/immSrc
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/aluOp
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/RSstation
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/memWrite
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/branch
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/isJAL
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/useImm
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/regWrite
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/stationRequest
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/isLUI
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/isAUIPC
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/isJALR
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/maindecoder/robWrite
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/extender/imm
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/extender/immSrc
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/extender/immExt
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/ALUdecoder/funct7
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/ALUdecoder/funct3
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/ALUdecoder/ALUOp
add wave -noupdate /cpuSim/cpu/decodeStage/decodeExtender/ALUdecoder/ALUControl
add wave -noupdate /cpuSim/cpu/decodeStage/regfile/clk
add wave -noupdate /cpuSim/cpu/decodeStage/regfile/regWrite
add wave -noupdate /cpuSim/cpu/decodeStage/regfile/address1
add wave -noupdate /cpuSim/cpu/decodeStage/regfile/address2
add wave -noupdate /cpuSim/cpu/decodeStage/regfile/wraddress
add wave -noupdate /cpuSim/cpu/decodeStage/regfile/wdata
add wave -noupdate /cpuSim/cpu/decodeStage/regfile/regValue1
add wave -noupdate /cpuSim/cpu/decodeStage/regfile/regValue2
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/clk
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/we
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/reset
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/validCommit
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/regWrite
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/rs1
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/rs2
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/destReg
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/destRegR
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/regCommit
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/statusRestore
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/destROB
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/commitROB
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/rob1
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/rob2
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/regStatusSnap
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/busy1
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/busy2
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/busyVectorI
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/busyVectorF
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/interRob1
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/interRob2
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/latestDpndency
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/interDep
add wave -noupdate /cpuSim/cpu/decodeStage/regTable/dependent
add wave -noupdate /cpuSim/cpu/instrRenameStage/operand1
add wave -noupdate /cpuSim/cpu/instrRenameStage/operand2
add wave -noupdate /cpuSim/cpu/instrRenameStage/robValue1
add wave -noupdate /cpuSim/cpu/instrRenameStage/robValue2
add wave -noupdate /cpuSim/cpu/instrRenameStage/ALUControl
add wave -noupdate /cpuSim/cpu/instrRenameStage/rob1
add wave -noupdate /cpuSim/cpu/instrRenameStage/rob2
add wave -noupdate /cpuSim/cpu/instrRenameStage/branchFunct3
add wave -noupdate /cpuSim/cpu/instrRenameStage/immExt
add wave -noupdate /cpuSim/cpu/instrRenameStage/pc
add wave -noupdate /cpuSim/cpu/instrRenameStage/RSstation
add wave -noupdate /cpuSim/cpu/instrRenameStage/state
add wave -noupdate /cpuSim/cpu/instrRenameStage/branch
add wave -noupdate /cpuSim/cpu/instrRenameStage/isJAL
add wave -noupdate /cpuSim/cpu/instrRenameStage/useImm
add wave -noupdate /cpuSim/cpu/instrRenameStage/regWrite
add wave -noupdate /cpuSim/cpu/instrRenameStage/redirect
add wave -noupdate /cpuSim/cpu/instrRenameStage/isJALR
add wave -noupdate /cpuSim/cpu/instrRenameStage/isLUI
add wave -noupdate /cpuSim/cpu/instrRenameStage/isAUIPC
add wave -noupdate /cpuSim/cpu/instrRenameStage/stationRequest
add wave -noupdate /cpuSim/cpu/instrRenameStage/busy1
add wave -noupdate /cpuSim/cpu/instrRenameStage/busy2
add wave -noupdate /cpuSim/cpu/instrRenameStage/clk
add wave -noupdate /cpuSim/cpu/instrRenameStage/branchBusyVector
add wave -noupdate /cpuSim/cpu/instrRenameStage/ALUBusyVector
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetPC
add wave -noupdate /cpuSim/cpu/instrRenameStage/earlyResult
add wave -noupdate /cpuSim/cpu/instrRenameStage/seqPC
add wave -noupdate /cpuSim/cpu/instrRenameStage/ready1
add wave -noupdate /cpuSim/cpu/instrRenameStage/ready2
add wave -noupdate /cpuSim/cpu/instrRenameStage/earlyWrite
add wave -noupdate /cpuSim/cpu/instrRenameStage/jump
add wave -noupdate /cpuSim/cpu/instrRenameStage/value1
add wave -noupdate /cpuSim/cpu/instrRenameStage/value2
add wave -noupdate /cpuSim/cpu/instrRenameStage/aluCntrl
add wave -noupdate /cpuSim/cpu/instrRenameStage/brnchCntrl
add wave -noupdate /cpuSim/cpu/instrRenameStage/branchRequests
add wave -noupdate /cpuSim/cpu/instrRenameStage/ALUFull
add wave -noupdate /cpuSim/cpu/instrRenameStage/branchFull
add wave -noupdate /cpuSim/cpu/instrRenameStage/ALURequests
add wave -noupdate /cpuSim/cpu/instrRenameStage/dataBus/result
add wave -noupdate /cpuSim/cpu/instrRenameStage/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/instrRenameStage/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/instrRenameStage/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/instrRenameStage/dataBus/isControl
add wave -noupdate /cpuSim/cpu/instrRenameStage/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/operand
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/ROBValue
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/rob
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/busy
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/ready
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/instrValue
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/dataBus/result
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/dataBus/isControl
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet1/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/operand
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/ROBValue
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/rob
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/busy
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/ready
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/instrValue
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/dataBus/result
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/dataBus/isControl
add wave -noupdate /cpuSim/cpu/instrRenameStage/valdet2/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/RSstation
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/stationRequest
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/branchBusyVector
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/ALUBusyVector
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/branchRequests
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/ALURequests
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/ALUFull
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/branchFull
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/ALUDone
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/branchDone
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/ALUMatch
add wave -noupdate /cpuSim/cpu/instrRenameStage/arbiter/branchMatch
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/PC
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/immExt
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/branch
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/isJAL
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/redirect
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/isLUI
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/isAUIPC
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/earlyWrite
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/jump
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/targetAddress
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/earlyResult
add wave -noupdate /cpuSim/cpu/instrRenameStage/targetResolver/seqPC
add wave -noupdate /cpuSim/cpu/aluReservationStation/ready1
add wave -noupdate /cpuSim/cpu/aluReservationStation/ready2
add wave -noupdate /cpuSim/cpu/aluReservationStation/clear
add wave -noupdate /cpuSim/cpu/aluReservationStation/clk
add wave -noupdate /cpuSim/cpu/aluReservationStation/execute
add wave -noupdate /cpuSim/cpu/aluReservationStation/writeRequests
add wave -noupdate /cpuSim/cpu/aluReservationStation/value1
add wave -noupdate /cpuSim/cpu/aluReservationStation/value2
add wave -noupdate /cpuSim/cpu/aluReservationStation/ALUControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/rob1
add wave -noupdate /cpuSim/cpu/aluReservationStation/rob2
add wave -noupdate /cpuSim/cpu/aluReservationStation/robInstr
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrRob
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrInfo
add wave -noupdate /cpuSim/cpu/aluReservationStation/busy
add wave -noupdate /cpuSim/cpu/aluReservationStation/src1
add wave -noupdate /cpuSim/cpu/aluReservationStation/src2
add wave -noupdate /cpuSim/cpu/aluReservationStation/busy1
add wave -noupdate /cpuSim/cpu/aluReservationStation/busy2
add wave -noupdate /cpuSim/cpu/aluReservationStation/busy3
add wave -noupdate /cpuSim/cpu/aluReservationStation/busy4
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectReq1
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectReq2
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectReq3
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectReq4
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrRob1
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrRob2
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrRob3
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrRob4
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrInfo1
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrInfo2
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrInfo3
add wave -noupdate /cpuSim/cpu/aluReservationStation/instrInfo4
add wave -noupdate /cpuSim/cpu/aluReservationStation/src1Instr1
add wave -noupdate /cpuSim/cpu/aluReservationStation/src1Instr2
add wave -noupdate /cpuSim/cpu/aluReservationStation/src1Instr3
add wave -noupdate /cpuSim/cpu/aluReservationStation/src1Instr4
add wave -noupdate /cpuSim/cpu/aluReservationStation/src2Instr1
add wave -noupdate /cpuSim/cpu/aluReservationStation/src2Instr2
add wave -noupdate /cpuSim/cpu/aluReservationStation/src2Instr3
add wave -noupdate /cpuSim/cpu/aluReservationStation/src2Instr4
add wave -noupdate /cpuSim/cpu/aluReservationStation/grants
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectionRequests
add wave -noupdate /cpuSim/cpu/aluReservationStation/operands1
add wave -noupdate /cpuSim/cpu/aluReservationStation/operands2
add wave -noupdate /cpuSim/cpu/aluReservationStation/sourceValue1
add wave -noupdate /cpuSim/cpu/aluReservationStation/sourceValue2
add wave -noupdate /cpuSim/cpu/aluReservationStation/robs
add wave -noupdate /cpuSim/cpu/aluReservationStation/chosenROB
add wave -noupdate /cpuSim/cpu/aluReservationStation/information
add wave -noupdate /cpuSim/cpu/aluReservationStation/toomanyNames
add wave -noupdate /cpuSim/cpu/aluReservationStation/dataBus/result
add wave -noupdate /cpuSim/cpu/aluReservationStation/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/aluReservationStation/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/aluReservationStation/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/aluReservationStation/dataBus/isControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/ready1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/ready2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/clear
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/writeReq
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/clk
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/selected
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/execute
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/value1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/value2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/ALUControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/rob1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/rob2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/robInstr
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/instrRob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/instrInfo
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/busy
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/selectReq
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/src1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/src2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/value1Ready
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/value2Ready
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/valRdy1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/valRdy2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/val1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/val2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/match1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/match2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/src1Rob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/src2Rob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/busyI
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/selectReq1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/selectReq2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/dataBus/result
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/dataBus/isControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry1/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/ready1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/ready2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/clear
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/writeReq
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/clk
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/selected
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/execute
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/value1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/value2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/ALUControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/rob1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/rob2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/robInstr
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/instrRob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/instrInfo
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/busy
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/selectReq
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/src1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/src2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/value1Ready
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/value2Ready
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/valRdy1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/valRdy2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/val1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/val2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/match1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/match2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/src1Rob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/src2Rob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/busyI
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/selectReq1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/selectReq2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/dataBus/result
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/dataBus/isControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry2/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/ready1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/ready2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/clear
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/writeReq
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/clk
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/selected
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/execute
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/value1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/value2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/ALUControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/rob1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/rob2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/robInstr
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/instrRob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/instrInfo
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/busy
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/selectReq
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/src1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/src2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/value1Ready
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/value2Ready
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/valRdy1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/valRdy2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/val1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/val2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/match1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/match2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/src1Rob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/src2Rob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/busyI
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/selectReq1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/selectReq2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/dataBus/result
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/dataBus/isControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry3/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/ready1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/ready2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/clear
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/writeReq
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/clk
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/selected
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/execute
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/value1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/value2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/ALUControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/rob1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/rob2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/robInstr
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/instrRob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/instrInfo
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/busy
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/selectReq
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/src1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/src2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/value1Ready
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/value2Ready
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/valRdy1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/valRdy2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/val1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/val2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/match1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/match2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/src1Rob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/src2Rob
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/busyI
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/selectReq1
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/selectReq2
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/dataBus/result
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/dataBus/isControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/entry4/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectLogic/requests
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectLogic/clear
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectLogic/clk
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectLogic/grants
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectLogic/nxtPointer
add wave -noupdate /cpuSim/cpu/aluReservationStation/selectLogic/pointer
add wave -noupdate /cpuSim/cpu/aluReservationStation/op1/sourceOperands
add wave -noupdate /cpuSim/cpu/aluReservationStation/op1/grants
add wave -noupdate /cpuSim/cpu/aluReservationStation/op1/operand
add wave -noupdate /cpuSim/cpu/aluReservationStation/op1/done
add wave -noupdate /cpuSim/cpu/aluReservationStation/op2/sourceOperands
add wave -noupdate /cpuSim/cpu/aluReservationStation/op2/grants
add wave -noupdate /cpuSim/cpu/aluReservationStation/op2/operand
add wave -noupdate /cpuSim/cpu/aluReservationStation/op2/done
add wave -noupdate /cpuSim/cpu/aluReservationStation/rob/sourceOperands
add wave -noupdate /cpuSim/cpu/aluReservationStation/rob/grants
add wave -noupdate /cpuSim/cpu/aluReservationStation/rob/operand
add wave -noupdate /cpuSim/cpu/aluReservationStation/rob/done
add wave -noupdate /cpuSim/cpu/aluReservationStation/info/sourceOperands
add wave -noupdate /cpuSim/cpu/aluReservationStation/info/grants
add wave -noupdate /cpuSim/cpu/aluReservationStation/info/operand
add wave -noupdate /cpuSim/cpu/aluReservationStation/info/done
add wave -noupdate /cpuSim/cpu/branchReservationStation/ready1
add wave -noupdate /cpuSim/cpu/branchReservationStation/ready2
add wave -noupdate /cpuSim/cpu/branchReservationStation/clear
add wave -noupdate /cpuSim/cpu/branchReservationStation/clk
add wave -noupdate /cpuSim/cpu/branchReservationStation/execute
add wave -noupdate /cpuSim/cpu/branchReservationStation/writeRequests
add wave -noupdate /cpuSim/cpu/branchReservationStation/value1
add wave -noupdate /cpuSim/cpu/branchReservationStation/value2
add wave -noupdate /cpuSim/cpu/branchReservationStation/predictedPC
add wave -noupdate /cpuSim/cpu/branchReservationStation/address
add wave -noupdate /cpuSim/cpu/branchReservationStation/seqPC
add wave -noupdate /cpuSim/cpu/branchReservationStation/branchControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/rob1
add wave -noupdate /cpuSim/cpu/branchReservationStation/rob2
add wave -noupdate /cpuSim/cpu/branchReservationStation/robInstr
add wave -noupdate /cpuSim/cpu/branchReservationStation/instrRob
add wave -noupdate /cpuSim/cpu/branchReservationStation/instrInfo
add wave -noupdate /cpuSim/cpu/branchReservationStation/busy
add wave -noupdate /cpuSim/cpu/branchReservationStation/src1
add wave -noupdate /cpuSim/cpu/branchReservationStation/src2
add wave -noupdate /cpuSim/cpu/branchReservationStation/predictedAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/targetAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/branchResult
add wave -noupdate /cpuSim/cpu/branchReservationStation/busy1
add wave -noupdate /cpuSim/cpu/branchReservationStation/busy2
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectReq1
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectReq2
add wave -noupdate /cpuSim/cpu/branchReservationStation/instrRob1
add wave -noupdate /cpuSim/cpu/branchReservationStation/instrRob2
add wave -noupdate /cpuSim/cpu/branchReservationStation/instrInfo1
add wave -noupdate /cpuSim/cpu/branchReservationStation/instrInfo2
add wave -noupdate /cpuSim/cpu/branchReservationStation/src1Instr1
add wave -noupdate /cpuSim/cpu/branchReservationStation/src1Instr2
add wave -noupdate /cpuSim/cpu/branchReservationStation/src2Instr1
add wave -noupdate /cpuSim/cpu/branchReservationStation/src2Instr2
add wave -noupdate /cpuSim/cpu/branchReservationStation/prediction1
add wave -noupdate /cpuSim/cpu/branchReservationStation/prediction2
add wave -noupdate /cpuSim/cpu/branchReservationStation/target1
add wave -noupdate /cpuSim/cpu/branchReservationStation/target2
add wave -noupdate /cpuSim/cpu/branchReservationStation/sequentialFetch
add wave -noupdate /cpuSim/cpu/branchReservationStation/nextFetch1
add wave -noupdate /cpuSim/cpu/branchReservationStation/nextFetch2
add wave -noupdate /cpuSim/cpu/branchReservationStation/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectionRequests
add wave -noupdate /cpuSim/cpu/branchReservationStation/operands1
add wave -noupdate /cpuSim/cpu/branchReservationStation/operands2
add wave -noupdate /cpuSim/cpu/branchReservationStation/redirection
add wave -noupdate /cpuSim/cpu/branchReservationStation/fetchAddr
add wave -noupdate /cpuSim/cpu/branchReservationStation/seqFetch
add wave -noupdate /cpuSim/cpu/branchReservationStation/sourceValue1
add wave -noupdate /cpuSim/cpu/branchReservationStation/sourceValue2
add wave -noupdate /cpuSim/cpu/branchReservationStation/robs
add wave -noupdate /cpuSim/cpu/branchReservationStation/chosenROB
add wave -noupdate /cpuSim/cpu/branchReservationStation/information
add wave -noupdate /cpuSim/cpu/branchReservationStation/toomanyNames
add wave -noupdate /cpuSim/cpu/branchReservationStation/btbPrediction
add wave -noupdate /cpuSim/cpu/branchReservationStation/actualAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/dataBus/result
add wave -noupdate /cpuSim/cpu/branchReservationStation/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/branchReservationStation/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/branchReservationStation/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/dataBus/isControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/ready1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/ready2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/clear
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/writeReq
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/clk
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/selected
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/execute
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/value1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/value2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/predictedPC
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/address
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/seqPC
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/branchControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/rob1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/rob2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/robInstr
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/instrRob
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/instrInfo
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/predictedAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/targetAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/branchResult
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/busy
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/selectReq
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/src1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/src2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/value1Ready
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/value2Ready
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/match1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/match2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/val1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/val2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/src1Rob
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/src2Rob
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/busyI
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/dataBus/result
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/dataBus/isControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry1/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/ready1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/ready2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/clear
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/writeReq
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/clk
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/selected
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/execute
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/value1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/value2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/predictedPC
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/address
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/seqPC
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/branchControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/rob1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/rob2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/robInstr
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/instrRob
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/instrInfo
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/predictedAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/targetAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/branchResult
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/busy
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/selectReq
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/src1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/src2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/value1Ready
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/value2Ready
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/match1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/match2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/val1
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/val2
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/src1Rob
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/src2Rob
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/busyI
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/dataBus/result
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/dataBus/isControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/entry2/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectLogic/requests
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectLogic/clear
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectLogic/clk
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectLogic/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectLogic/nxtPointer
add wave -noupdate /cpuSim/cpu/branchReservationStation/selectLogic/pointer
add wave -noupdate /cpuSim/cpu/branchReservationStation/op1/sourceOperands
add wave -noupdate /cpuSim/cpu/branchReservationStation/op1/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/op1/operand
add wave -noupdate /cpuSim/cpu/branchReservationStation/op1/done
add wave -noupdate /cpuSim/cpu/branchReservationStation/op2/sourceOperands
add wave -noupdate /cpuSim/cpu/branchReservationStation/op2/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/op2/operand
add wave -noupdate /cpuSim/cpu/branchReservationStation/op2/done
add wave -noupdate /cpuSim/cpu/branchReservationStation/rob/sourceOperands
add wave -noupdate /cpuSim/cpu/branchReservationStation/rob/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/rob/operand
add wave -noupdate /cpuSim/cpu/branchReservationStation/rob/done
add wave -noupdate /cpuSim/cpu/branchReservationStation/info/sourceOperands
add wave -noupdate /cpuSim/cpu/branchReservationStation/info/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/info/operand
add wave -noupdate /cpuSim/cpu/branchReservationStation/info/done
add wave -noupdate /cpuSim/cpu/branchReservationStation/predictor/sourceOperands
add wave -noupdate /cpuSim/cpu/branchReservationStation/predictor/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/predictor/operand
add wave -noupdate /cpuSim/cpu/branchReservationStation/predictor/done
add wave -noupdate /cpuSim/cpu/branchReservationStation/addressor/sourceOperands
add wave -noupdate /cpuSim/cpu/branchReservationStation/addressor/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/addressor/operand
add wave -noupdate /cpuSim/cpu/branchReservationStation/addressor/done
add wave -noupdate /cpuSim/cpu/branchReservationStation/fetchor/sourceOperands
add wave -noupdate /cpuSim/cpu/branchReservationStation/fetchor/grants
add wave -noupdate /cpuSim/cpu/branchReservationStation/fetchor/operand
add wave -noupdate /cpuSim/cpu/branchReservationStation/fetchor/done
add wave -noupdate /cpuSim/cpu/executeStage/bSrc1
add wave -noupdate /cpuSim/cpu/executeStage/bSrc2
add wave -noupdate /cpuSim/cpu/executeStage/targetAddress
add wave -noupdate /cpuSim/cpu/executeStage/predictedPC
add wave -noupdate /cpuSim/cpu/executeStage/branchResult
add wave -noupdate /cpuSim/cpu/executeStage/branchControl
add wave -noupdate /cpuSim/cpu/executeStage/src1
add wave -noupdate /cpuSim/cpu/executeStage/src2
add wave -noupdate /cpuSim/cpu/executeStage/ALUControl
add wave -noupdate /cpuSim/cpu/executeStage/ALURob
add wave -noupdate /cpuSim/cpu/executeStage/branchRob
add wave -noupdate /cpuSim/cpu/executeStage/clk
add wave -noupdate /cpuSim/cpu/executeStage/aluAvailable
add wave -noupdate /cpuSim/cpu/executeStage/branchAvailable
add wave -noupdate /cpuSim/cpu/executeStage/result
add wave -noupdate /cpuSim/cpu/executeStage/ALURequest
add wave -noupdate /cpuSim/cpu/executeStage/correctAddress
add wave -noupdate /cpuSim/cpu/executeStage/branchResultE
add wave -noupdate /cpuSim/cpu/executeStage/nextState
add wave -noupdate /cpuSim/cpu/executeStage/mispredict
add wave -noupdate /cpuSim/cpu/executeStage/misdirect
add wave -noupdate /cpuSim/cpu/executeStage/reset
add wave -noupdate /cpuSim/cpu/executeStage/writeBTB
add wave -noupdate /cpuSim/cpu/executeStage/request
add wave -noupdate /cpuSim/cpu/executeStage/takenBranch
add wave -noupdate /cpuSim/cpu/executeStage/controlPC
add wave -noupdate /cpuSim/cpu/executeStage/dataBus/result
add wave -noupdate /cpuSim/cpu/executeStage/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/executeStage/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/executeStage/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/executeStage/dataBus/isControl
add wave -noupdate /cpuSim/cpu/executeStage/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/src1
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/src2
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/predictedPC
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/targetAddress
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/branchResult
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/branchControl
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/correctAddress
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/branchResultE
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/nextState
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/mispredict
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/misdirect
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/reset
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/takenBranch
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/writeBTB
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/request
add wave -noupdate /cpuSim/cpu/executeStage/branchUnit/tempAddress
add wave -noupdate /cpuSim/cpu/executeStage/computeUnit/src1
add wave -noupdate /cpuSim/cpu/executeStage/computeUnit/src2
add wave -noupdate /cpuSim/cpu/executeStage/computeUnit/ALUControl
add wave -noupdate /cpuSim/cpu/executeStage/computeUnit/result
add wave -noupdate /cpuSim/cpu/executeStage/computeUnit/ALURequest
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/controlPC
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/ALURob
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/branchRob
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/ALUResult
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/branchResult
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/fetchAddress
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/ALURequest
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/branchRequest
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/clk
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/aluAvailable
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/branchAvailable
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/nxtPointer
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/pointer
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/value
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/grant
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/rob
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/we
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/controlFlow
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/dataBus/result
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/dataBus/isControl
add wave -noupdate /cpuSim/cpu/executeStage/dataBusArbiter/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/rob/rob1
add wave -noupdate /cpuSim/cpu/rob/rob2
add wave -noupdate /cpuSim/cpu/rob/robWrite
add wave -noupdate /cpuSim/cpu/rob/freeze
add wave -noupdate /cpuSim/cpu/rob/globalReset
add wave -noupdate /cpuSim/cpu/rob/ROBValue1
add wave -noupdate /cpuSim/cpu/rob/ROBValue2
add wave -noupdate /cpuSim/cpu/rob/valid1
add wave -noupdate /cpuSim/cpu/rob/valid2
add wave -noupdate /cpuSim/cpu/rob/full
add wave -noupdate /cpuSim/cpu/rob/robAllocation
add wave -noupdate /cpuSim/cpu/rob/commitRob
add wave -noupdate /cpuSim/cpu/rob/clk
add wave -noupdate /cpuSim/cpu/rob/write_ptr
add wave -noupdate /cpuSim/cpu/rob/read_ptr
add wave -noupdate /cpuSim/cpu/rob/rdy
add wave -noupdate /cpuSim/cpu/rob/bypass
add wave -noupdate /cpuSim/cpu/rob/commitRdy
add wave -noupdate /cpuSim/cpu/rob/value
add wave -noupdate /cpuSim/cpu/rob/target
add wave -noupdate /cpuSim/cpu/rob/pcControl
add wave -noupdate /cpuSim/cpu/rob/result
add wave -noupdate /cpuSim/cpu/rob/targetAddress
add wave -noupdate /cpuSim/cpu/rob/statusSnap
add wave -noupdate /cpuSim/cpu/rob/oldPC
add wave -noupdate /cpuSim/cpu/rob/destCommit
add wave -noupdate /cpuSim/cpu/rob/commitInfo
add wave -noupdate /cpuSim/cpu/rob/controlFlow
add wave -noupdate /cpuSim/cpu/rob/previousIndex
add wave -noupdate /cpuSim/cpu/rob/dataBus/result
add wave -noupdate /cpuSim/cpu/rob/dataBus/robEntry
add wave -noupdate /cpuSim/cpu/rob/dataBus/validBroadcast
add wave -noupdate /cpuSim/cpu/rob/dataBus/targetAddress
add wave -noupdate /cpuSim/cpu/rob/dataBus/isControl
add wave -noupdate /cpuSim/cpu/rob/dataBus/pcControl
add wave -noupdate /cpuSim/cpu/rob/inputBus/instrPC
add wave -noupdate /cpuSim/cpu/rob/inputBus/oldPC
add wave -noupdate /cpuSim/cpu/rob/inputBus/regStatus
add wave -noupdate /cpuSim/cpu/rob/inputBus/statusSnap
add wave -noupdate /cpuSim/cpu/rob/inputBus/targetAddress
add wave -noupdate /cpuSim/cpu/rob/inputBus/result
add wave -noupdate /cpuSim/cpu/rob/inputBus/PHTIndex
add wave -noupdate /cpuSim/cpu/rob/inputBus/previousIndex
add wave -noupdate /cpuSim/cpu/rob/inputBus/controlFlow
add wave -noupdate /cpuSim/cpu/rob/inputBus/destination
add wave -noupdate /cpuSim/cpu/rob/inputBus/destCommit
add wave -noupdate /cpuSim/cpu/rob/inputBus/commitInfo
add wave -noupdate /cpuSim/cpu/rob/inputBus/validCommit
add wave -noupdate /cpuSim/cpu/rob/outputBus/instrPC
add wave -noupdate /cpuSim/cpu/rob/outputBus/oldPC
add wave -noupdate /cpuSim/cpu/rob/outputBus/regStatus
add wave -noupdate /cpuSim/cpu/rob/outputBus/statusSnap
add wave -noupdate /cpuSim/cpu/rob/outputBus/targetAddress
add wave -noupdate /cpuSim/cpu/rob/outputBus/result
add wave -noupdate /cpuSim/cpu/rob/outputBus/PHTIndex
add wave -noupdate /cpuSim/cpu/rob/outputBus/previousIndex
add wave -noupdate /cpuSim/cpu/rob/outputBus/controlFlow
add wave -noupdate /cpuSim/cpu/rob/outputBus/destination
add wave -noupdate /cpuSim/cpu/rob/outputBus/destCommit
add wave -noupdate /cpuSim/cpu/rob/outputBus/commitInfo
add wave -noupdate /cpuSim/cpu/rob/outputBus/validCommit
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/rob1
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/rob2
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/ROBcommit
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/clk
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/wcommit
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/ROBValue1
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/ROBValue2
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/valid1
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/valid2
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/value1
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/value2
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/ready1
add wave -noupdate /cpuSim/cpu/rob/renamebuffer/ready2
add wave -noupdate -label dataBus.result /cpuSim/cpu/rob/renamebuffer/dataBus/result
add wave -noupdate -label dataBus.robEntry /cpuSim/cpu/rob/renamebuffer/dataBus/robEntry
add wave -noupdate -label dataBus.validBroadcast /cpuSim/cpu/rob/renamebuffer/dataBus/validBroadcast
add wave -noupdate -label dataBustargetAddre /cpuSim/cpu/rob/renamebuffer/dataBus/targetAddress
add wave -noupdate -label dataBusIsControl /cpuSim/cpu/rob/renamebuffer/dataBus/isControl
add wave -noupdate -label dataBusPcControl /cpuSim/cpu/rob/renamebuffer/dataBus/pcControl
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {8100 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {100 ns}
